language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - PHPUNIT_CONFIG="phpunit.xml"
  - PHPUNIT_CONFIG="phpunit.bootstrapless.xml"

before_script:
  - composer install --dev --prefer-source

script: "[ -f $PHPUNIT_CONFIG ] && ./vendor/bin/phpunit -c $PHPUNIT_CONFIG || ./vendor/bin/phpunit -c $PHPUNIT_CONFIG.dist"
